### ISSUE TITLE
A problem while installing poly-markdown from epla

### ISSUE THREAD

**Issue by crotoc** [polymode/poly-markdown#1]
Hi, I really like the idea of using markdown in emacs and thanks for your great work!

My emacs is 26.1 and I want to install polymode. While compling this package, it gives the error:

Compiling file /home/chenr6/.emacs.d/elpa/poly-markdown-20180905.1437/poly-markdown.el at Wed Sep  5 15:47:39 2018                                          
Entering directory ‘/home/chenr6/.emacs.d/elpa/poly-markdown-20180905.1437/’                                                                                
poly-markdown.el:124:1:Error: No pm-polymode config object with name ‘pm-poly/pm-poly/markdown’   

Please help me! Thanks!

**Comment by crotoc** [comment]
I think it's the problem at line 124 that a extra directory of pm-poly/ is added.

**Comment by vspinu** [comment]
Yeh. I see this in MELPA but not in local build from source. Looking into it.

**Comment by crotoc** [comment]
Thanks! Can you let me know how to build from source? I would like have a try! :)

**Comment by crotoc** [comment]
Now I manually installed the package and it works, but installation from package-install of MEPLA. Can you help me check it if you have time? Thanks!

**Comment by vspinu** [comment]
You mean you cannot install from MELPA? It should work as I pull them from melpa for some tests. If not could you please open a new issue with the more detailed description of the problem?
