### ISSUE TITLE
Use add-hook instead of add to list

### ISSUE THREAD

**Issue by czipperz** [polymode/poly-markdown#10]
https://github.com/polymode/poly-markdown/blob/5ee48544036e51d47488e8dcab11a3844b1baad8/poly-markdown.el#L135

This allows for using this automatically in all markdown files instead of just files ending in .md.  This is useful for buffers generated by edit-indirect and for alternative file extensions.

**Comment by czipperz** [comment]
Example code:

```
(add-hook 'markdown-mode-hook #'poly-markdown-mode)
```

**Comment by vspinu** [comment]
It's not needed in all markdown files. The canonical way is to extend the markdown mode and assoc into auto-mode alist. 

https://github.com/polymode/poly-R/blob/master/poly-R.el#L92

You can add hook locally if you want but that will mess child modes and also modes which use markdown as host or (especially) innermode.

**Comment by czipperz** [comment]
Really we shouldn't be adding the hook at all, instead let the user enable it manually.  That's what I've seen

**Comment by czipperz** [comment]
>The canonical way is to extend the markdown mode and assoc into auto-mode alist.

That's definitely not something I've seen.  [magit-filenotify](https://github.com/ruediger/magit-filenotify) recommends `add-hook`.  [racer](https://github.com/racer-rust/emacs-racer) uses the same.  The wiki recommends `add-hook` for [paredit](https://www.emacswiki.org/emacs/ParEdit).

Where did you get this idea?

**Comment by vspinu** [comment]
> That's definitely not something I've seen

You haven't seen enough. Those functionality enhancers designed as to be used in hooks. Polymodes are proper emacs modes. Emacs modes are installed in auto-mode alist. End of story. 

If a polymode is intended to be used as a minor-mode then yes, it should be placed in a hook, but poly-markdown is generally not. 

The technical reason that I have given above is a very severe one. If I load it in markdown hook then child modes like `poly-markdown+r-mode` will trigger `poly-markdown-mode`, if `markdown-mode` is used as a innermode it will trigger the `poly-markdown-mode` etc.
