### ISSUE TITLE
`fill-paragraph` causes Lisp nesting

### ISSUE THREAD

**Issue by sheepduke** [polymode/poly-markdown#11]
First thank you for your work. And I used `poly-mode` to develop my own plugin. The `poly-mode` is awesome and far better than `mmm-mode` IMO. I really appreciate it.

I found a bug.

When `poly-markdown-mode` is enabled, executing `fill-paragraph` causes the following error:

```
eieio-oref: Lisp nesting exceeds ‘max-lisp-eval-depth’
```

Could you please help?

**Comment by sheepduke** [comment]
Wait...I found the solution.

My original configuration is: 

```emacs-lisp
(use-package poly-markdown
  :ensure
  
  :hook
  (markdown-mode . poly-markdown-mode))
```

I tried to remove the `poly-markdown-mode` from `markdown-mode-hook`, and the problem just disappeared!

Could you please elaborate on it? I am really curious about the true cause.

**Comment by vspinu** [comment]
`poly-markdown-mode` is not designed to be used as a minor mode, and even though it could, some corner issues could happen. This one is probably one of them but its nature is not clear to me. I will investigate. It might be an incantation of some deeper problem.

**Comment by sheepduke** [comment]
You are right. My mistake was that I tried to enable `poly-markdown-mode` in `markdown-mode`.

I think it is better to give a warning on the README file to avoid further misunderstanding...

**Comment by sheepduke** [comment]
/close 
Closing...
