### ISSUE TITLE
Errors running polymode

### ISSUE THREAD

**Issue by pixbuf** [polymode/poly-markdown#15]
I had installed polymode a long time ago manually. Then recently all of a sudden it became very strange: highlighting passages randomly, <TAB> would move to the end of a chunk instead of indenting the line, etc. So, I decided to update it. I used install-packages and got this result:
 
>   poly-R             0.2           installed             Various polymodes for R language
>   markdown-mode      2.3           dependency            Major mode for Markdown-formatted text
>   poly-markdown      0.2           dependency            Polymode for markdown-mode
>   poly-noweb         0.2           dependency            Polymode for noweb
>   polymode           0.2           dependency            Extensible framework for multiple major modes

And I added these lines to ~/.emacs:

> ;;poly-markdown
> (setq load-path
> (append '("/home/sl70/.emacs.d/elpa/polymode-0.2/" "/home/sl70/.emacs.d/elpa/poly-markdown-0.2/")
> load-path))
> (require 'poly-markdown)
> (add-to-list 'auto-mode-alist '("\.md" . poly-markdown-mode))
> 
> (add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode))
> 
> 

But when I open an Rmarkdown document I get all kinds of inscrutable errors:
`
Debugger entered--Lisp error: (invalid-slot-name "#<pm-polymode latex-root>" :lighter)
  signal(invalid-slot-name ("#<pm-polymode latex-root>" :lighter))
  slot-missing(#<pm-polymode latex-root> :lighter oref)
  eieio-oref(#<pm-polymode latex-root> :lighter)
  byte-code("\302\303!\210\304\305\306\001J\307\"\304\310\004!\204X\0\003\262\001\002J\304\211\002\203V\0\311\003\312\"\205(\0\306\003\312\"\262\002\0019\203@\0\310\002J!\203@\0\001J\262\007\304\262\003\202\031\0\311\003\313\"\205K\0\306\003\313\"\262\003\314\004\003\"\262\004\202\031\0\266\003\003\204_\0\010\262\004\315\316\002\304\211\317\006\011D$!\210\320\303\321\"\210\322\303\003\011#\266\004\207" [polymode-mode-map poly-noweb-mode-map make-variable-buffer-local poly-noweb-mode nil poly-latex-root-polymode eieio-oref :lighter keymapp slot-boundp :map :parent-instance append (lambda (def-tmp-var) (defvar poly-noweb-mode-map def-tmp-var "Keymap for noweb polymode.")) easy-mmode-define-keymap :inherit defalias #f(compiled-function (&optional arg) "noweb polymode.\n\n\\{poly-noweb-mode-map}" (interactive nil) #<bytecode 0x1085565>) add-minor-mode] 11)
  require(poly-noweb)
  byte-code("\300\301!\210\300\302!\210\300\303\304\305#\210\306\307\304\310\311\301%\210\312\313\314\315\316DD\317\311\320\321\322&\007\210\300\323!\210\324\325\326\304#\210\327\211\203Q\0\211@\325\001N\203J\0\326\001N\204J\0\330\326\002\325\004N#\210\001A\266\202\2020\0\210\331\325\326\332#\210\333\326!\207" [require polymode ess-mode ess-r-mode nil t custom-declare-group poly-R "Settings for poly-R polymodes" :group custom-declare-variable poly-r-root-polymode funcall function #f(compiled-function () #<bytecode 0xed8bb5>) "Root polymode with R host intended to be inherited from." polymodes :type object poly-noweb defvaralias pm-inner/noweb-R poly-r-noweb-innermode (saved-value saved-variable-comment) put make-obsolete-variable "v0.2" makunbound] 8)
  poly-markdown+r-mode()
  set-auto-mode-0(poly-markdown+r-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer measure_summary.Rmd> "~/work/Carnegie/measures-network/measure_summary.Rmd" nil nil "~/work/Carnegie/measures-network/measure_summary.Rmd" (604349673 2054))
  find-file-noselect("/home/sl70/work/Carnegie/measures-network/measure_summary.Rmd")
  #f(compiled-function (displayable-buffers dir line column name) #<bytecode 0x1d9b73>)((nil) "~/work/Carnegie/measures-network/" (0) (0) "measure_summary.Rmd")
  command-line-1(("measure_summary.Rmd"))
  command-line()
  normal-top-level()
`
I tried searching for the error but couldn't find anything useful. Any help will be very much appreciated.

**Comment by pixbuf** [comment]
Never mind. I uninstalled all the packages and only installed poly-R and polymode and now it works.

**Comment by vspinu** [comment]
Happy it worked out by itself :)
