### ISSUE TITLE
Overly aggressive inline fontification for multi-word inline code

### ISSUE THREAD

**Issue by ashiklom** [polymode/poly-markdown#5]
Inline code that contains a space is incorrectly fontified in the "fallback" mode. For example, the inline code `git status` is interpreted as just `status` in mode `git`, which is then incorrectly fontified in the fallback mode. (A workaround for my own documents is to insert a space after the opening backtick, but that's a problem when editing others' documents).

I'm not convinced that inline major-mode-specific fontification is a sensible default. AFAIK, it is not supported by GitHub- or pandoc-flavored markdown, which are two of the most common flavors. Perhaps it would be better to control it via a variable? For instance, something like `poly-markdown-inline-modes` -- if `nil`, just use the default Markdown fontification for inline code).

**Comment by vspinu** [comment]
The inline Fallback should be the markdown mode by design. I will have a look.

Unfortunately the emacs eieio doesn't deliver on the object customization part and customizing pm-poly/markdown doesn't quite work currently. You can remove the inner code mode with a bit of elisp:

```el
(with-slots (innermodes) pm-poly/markdown
  (setq innermodes (delq 'pm-inner/markdown-inline-code innermodes)))
```

**Comment by vspinu** [comment]
I have made some improvements. First the fallback is now the host mode, second you can set `polymode-default-inner-mode` to overwrite that fallback for code chunks which were not identified. 

The problem still remains with those cases when the fist word matches an existing mode, but the content is not the code. I am thinking of enforcing `{mode} ...` syntax for inner code blocks. What do you think?

I believe the lax inner code detection was added because rmarkdown supports it that way.

**Comment by vspinu** [comment]
> I am thinking of enforcing {mode} ... syntax for inner code blocks. What do you think?

Well, given that currently the core users of polymode are Rmd users and there are plenty of Rmd files with this syntax already, I am leaving it as it is for now. Given that there is an easy workaround for rare cases when the actual mode is not needed, I think it's a bearable feature.

**Comment by ashiklom** [comment]
Thanks for resolving this, and for the suggestion about removing inner code mode!

FWIW, I agree that it's better _not_ to enforce the `{mode} ...` inner code block syntax, precisely for the reasons you describe.

---

(In case others come across this thread, here's the commit with the fix: https://github.com/polymode/polymode/commit/aedfa629c4e58e539dde954c04d315106ab6a478)
