### ISSUE TITLE
$ character starts latex mode even inside fenced block

### ISSUE THREAD

**Issue by jrvarma** [polymode/poly-markdown#6]
When using `poly-markdown`, the `$` character starts `LaTex` mode even inside fenced block. In a fenced block the `$` character is just a literal character and should not start `LaTex` mode. 

I am using `poly-markdown-0.1.5` and `emacs 26.1`

**Comment by vspinu** [comment]
This one is a bad one. I don't know how to fix this generically without complicating the span logic by a huge extent. I guess I will just restrict the markdown math span to single lines for now.

**Comment by vspinu** [comment]
Ok. I figured out a simple solutions. Thanks for reporting this.

**Comment by jrvarma** [comment]
Could you please push this into Melpa Stable or at least into Melpa. If this is not likely to happen soon, then I can try installing manually using git clone.

**Comment by vspinu** [comment]
It's always on Melpa. I will tag for Melpa Stable tomorrow.

**Comment by jrvarma** [comment]
Problem persists after upgrading `polymode`, `poly-markdown`, `poly-R` and `poly-noweb` to 0.2 from Melpa Stable.  

Minimal working example of the problem is 
```
echo $PATH
```

- As I type `echo $PATH` inside the fenced block in a markdown file, `polymode` switches the buffer mode from `Markdown PM` to `LaTex/P PM` as soon as I type the `$`. 
- It will come back to `Markdown PM` if I type another `$` without any intervening spaces or new line (say `echo $PATH$`)
- But if instead I start a new line and I type a `$` on the new line (say, `echo $HOME`), it does not return to `Markdown PM`. 
- The result is that after one line in a fenced block containing a single `$`, the buffer remains in `LaTex/P PM` mode till the end of the file regardless of how many more  `$`'s it contains.

I have confirmed this behaviour with `emacs -Q`  after running the following in a scratch buffer
```
(require 'package)
(package-initialize nil)
```

**Comment by vspinu** [comment]
This is only in unnamed blocks right? In named ones things behave as expected right?

**Comment by jrvarma** [comment]
Absolutely. Never thought that just naming the block would solve the problem!

**Comment by vspinu** [comment]
The unnamed blocks (aka those without an explicit mode) are not treated by polymode in any special way. This is why you get this results. Fixing this is a bit tricky mostly for reasons described in #9 but should be possible after the recent core rewrite.

**Comment by jrvarma** [comment]
Using an explicit mode is good practice in any case, and also makes editing the block in `emacs` easier. If nothing else, one can always use `text` as the mode. I am happy with the current solution.

Thanks again for a wonderful `emacs` package.

**Comment by jcubic** [comment]
I have same issue with dollar inside JavaScript code block, with latest version from Melpa.
